# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        hostel:
            properties:
                id:
                    type: text
                name:
                    type: text
                description:
                    type: text
                enabled:
                    type: boolean
                position:
                    type: integer
                starNumber:
                    type: integer
                parking:
                    type: boolean
                breakfast:
                    type: boolean
                animalsAllowed:
                    type: boolean
                children:
                    type: boolean
                mobilePaymentAllowed:
                    type: boolean
                cardPaymentAllowed:
                    type: boolean
                createdAt:
                    type: date
                rooms:
                    type: nested
                    properties:
                        price:
                            type: integer
                location:
                    type: nested
                    properties:
                        city:
                            type: nested
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: text
                equipments:
                    type: nested
                    properties:
                        id:
                            type: integer
                        name:
                            type: text
            persistence:
                driver: orm
                model: App\Entity\Hostel
                listener:
                    defer: true
                    logger: true
                elastica_to_model_transformer:
                    ignore_missing: true
        category:
            properties:
                name:
                    type: text
                position:
                    type: integer
                slug:
                    type: text
                enabled:
                    type: boolean
            persistence:
                driver: orm
                model: App\Entity\Category
                listener:
                    defer: true
                    logger: true
                elastica_to_model_transformer:
                    ignore_missing: true
        city:
            properties:
                name:
                    type: text
                position:
                    type: integer
                slug:
                    type: text
                enabled:
                    type: boolean
            persistence:
                driver: orm
                model: App\Entity\City
                listener:
                    defer: true
                    logger: true
                elastica_to_model_transformer:
                    ignore_missing: true
        location:
            properties:
                city:
                    type: nested
                    properties:
                        name:
                            type: text
                town:
                    type: text
                detail:
                    type: text
                latitude:
                    type: text
                longitude:
                    type: text
            persistence:
                driver: orm
                model: App\Entity\Location
                listener:
                    defer: true
                    logger: true
                elastica_to_model_transformer:
                    ignore_missing: true
        equipment:
            properties:
                name:
                    type: text
                    #fielddata: true
                position:
                    type: integer
            persistence:
                driver: orm
                model: App\Entity\Equipment
                listener:
                    defer: true
                    logger: true
                elastica_to_model_transformer:
                    ignore_missing: true
        banner:
            properties:
                type:
                    type: text
                location:
                    type: text
                position:
                    type: integer
            persistence:
                driver: orm
                model: App\Entity\Banner
                listener:
                    defer: true
                    logger: true
                elastica_to_model_transformer:
                    ignore_missing: true





#fos_elastica:
#    clients:
#        default: { url: '%env(ELASTICSEARCH_URL)%' }
#    indexes:
#        #app:
#            #index_name: app_%kernel.environment%
#        advert:
#            properties:
#                id:
#                    type: integer
#                title:
#                    type: text
#                    boost: 5
#                description:
#                    type: text
#                category:
#                    type: nested
#                    properties:
#                        id:
#                            type: integer
#                        name:
#                            type: text
#                        slug:
#                            type: text
#                subCategory:
#                    type: nested
#                    properties:
#                        id:
#                            type: integer
#                        name:
#                            type: text
#                        slug:
#                            type: text
#                subDivision:
#                    type: nested
#                    properties:
#                        id:
#                            type: integer
#                        name:
#                            type: text
#                        slug:
#                            type: text
#                price:
#                    type: integer
#                type:
#                    type: text
#                    boost: 5
#                autoYear:
#                    type: text
#                position:
#                    type: integer
#                marque:
#                    type: text
#                model:
#                    type: text
#                typeCarburant:
#                    type: text
#                immobilierState:
#                    type: text
#                nombrePiece:
#                    type: text
#                nombreChambre:
#                    type: integer
#                nombreSalleBain:
#                    type: integer
#                access: ~
#                proximite: ~
#                interior: ~
#                exterior: ~
#                state:
#                    type: text
#                kilo:
#                    type: integer
#                surface:
#                    type: integer
#                traitement:
#                    type: text
#                location:
#                    type: nested
#                    properties:
#                        id:
#                            type: integer
#                        name:
#                            type: text
#                        detail:
#                            type: text
##                        lat:
##                            type: geo_point
##                        lng:
##                            type: geo_point
#                validated:
#                    type: boolean
#                validatedAt:
#                    type: date
#                denied:
#                    type: boolean
#                deniedAt:
#                    type: date
#                deleted:
#                    type: boolean
#                deletedAt:
#                    type: date
#                optionPhoto:
#                    type: boolean
#                optionAdHeadEnd:
#                    type: date
#                optionAdUrgentsEnd:
#                    type: date
#                optionAdGalleryEnd:
#                    type: date
#                optionAdVedetteEnd:
#                    type: date
#                optionAdEncadreEnd:
#                    type: date
#            persistence:
#                driver: orm
#                model: App\Entity\Advert
#                listener: ~
#

