# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: fr_CI
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    app.path.image_orphanage: '%kernel.cache_dir%/uploader/orphanage'
    image_resize_key: '%env(resolve:IMAGE_RESIZE_KEY)%'
    dkim_key: '%env(resolve:default::MAILER_DKIM)%'
    maintenance_dir: '%env(resolve:MAINTENANCE_DIR)%'
    fedapay_secret_key: '%env(FEDAPAY_SECRET)%'
    hsms_client_id: '%env(HSMS_CLIENT_ID)%'
    hsms_client_secret: '%env(HSMS_CLIENT_SECRET)%'
    hsms_token: '%env(HSMS_TOKEN)%'
    app.path.user: /uploads/images/user
    app.path.category: /uploads/images/categories
    app.path.city: /uploads/images/cities
    app.path.settings: /uploads/images/logo
    app.path.hostel: /uploads/images/hostels
    app.path.banner: /uploads/images/banners
    app.path.banner_mobile: /uploads/images/banners_mobile

    app_name_property_prefix: name
    app_city_property_prefix: city
    app_country_property_prefix: country
    app_description_property_prefix: description
    app_location_property_prefix: location
    app_position_property_prefix: position
    app_equipment_property_prefix: equipments
    app_room_equipment_property_prefix: roomEquipments
    app_category_property_prefix: category
    app_star_number_property_prefix: starNumber

    app_equipment_property: equipments.id
    app_city_property: location.city
    app_city_name_property: location.city.name
    app_enabled_property: enabled
    app_closed_property: closed
    app_id_property: id
    app_room_price_property_prefix: price
    app_room_property_prefix: rooms
    app_created_at_property_prefix: createdAt
    app_average_rating_property_prefix: averageRating
    app_occupant_property_prefix: occupant

    app_fuzziness: AUTO
    app_pagination_available_page_limits: [9, 18, 36]
    app_pagination_default_limit: 25
    app_hostel_filter_price_min: 0
    app_hostel_filter_price_max: 99000
    app_hostel_filter_price_step: 500

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Mailing\Mailer:
        arguments:
            $dkimKey: '%dkim_key%'

    App\Manager\ConfigurationFileManager:
        arguments:
            $maintenanceDirectory: '%maintenance_dir%'

    App\PropertyNameResolver\NameResolver:
        arguments:
            $propertyPrefix: '%app_name_property_prefix%'

    App\PropertyNameResolver\PriceNameResolver:
        arguments:
            $pricePropertyPrefix: '%app_room_price_property_prefix%'

    App\PropertyNameResolver\ConcatedPriceNameResolver:
        arguments:
            $propertyPrefix: '%app_room_property_prefix%'

    App\Provider\HostelProvider:
        tags:
            - { name: fos_elastica.pager_provider, index: hostel }

    App\Notifier\Transport\HSmsTransportFactory:
        parent: 'notifier.transport_factory.abstract'
        tags: ['texter.transport_factory']

    App\Api\State\UserStateProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'

    App\Api\State\FavoriteStateProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'

    App\Api\OpenApi\OpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@App\Api\OpenApi\OpenApiFactory.inner' ]
        autoconfigure: false

